name: Sync from Main Repo

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout staging repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.deploy_secret }}

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/IEEEDTUCS/IEEEWeb-2025.git
          git fetch upstream

      - name: Merge changes from main
        run: |
          git checkout main
          git merge upstream/main --no-edit || true
          git push origin main
