name: Sync from Main Repo

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DEPLOY_SECRET }} # must have repo scope
          fetch-depth: 0                      # fetch full history (important for merge)

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/IEEEDTUCS/IEEEWeb-2025.git
          git fetch upstream

      - name: Merge changes from upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit || true
          git push origin main
